name: ESLint

on:
  pull_request:
    branches:
      - "master"

defaults:
  run:
    shell: bash
    working-directory: lambda/custom

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      #run: eslint . --ext .js,.ts
      run: yarn run lint-check
